### ISSUE TITLE
Is synchronization or channel preferences export supported?

### ISSUE THREAD

**Issue by GeniusBroccoli** [Gmanicus/Youtube-Tabs#1]
Hi, great extension, but does any synchronization work, export parameters?

**Comment by Gmanicus** [comment]
Hi Broccoli!

Thank you!

Cloud-synchronization/exporting to another browser client is not a feature
just yet, but it is planned to be implemented soon.

However, I would like to note so that it isn't a surprise: I am planning to
add a paid tier for the extension, and that would be the first paid
feature. The current features will be free and will continue to be expanded
upon, but I will place some secondary features behind a very cheap paywall
(at the moment, my plan is $3 USD for access to absolutely everything).

2.0 is almost release-ready. I just need to squash a few bugs and finalize
a few features. That may be a few weeks away as of yet.

2.1 should include the cloud-sync feature and paid tier, but that could be
anywhere from a few weeks to a few months away unfortunately. All depends
on the time I'll have available.

Feel free to clone the repo and load into your browser to have access to
the most recent features, but please note that there are likely a number of
outstanding issues that I have yet to fix due to the 2.0 overhaul.

**Comment by GeniusBroccoli** [comment]
> 

Thanks for the answer, good luck with the development. I noticed one bug, maybe you know about it, an extension button is built into the subscribe button and it all starts blinking (Firefox).
![ззз](https://user-images.githubusercontent.com/18056785/196675475-69ac4c2e-128f-4388-8227-0fecaecbd9ac.gif)

And I see help window each time I open youtube.

**Comment by Gmanicus** [comment]
Thank you. I appreciate it, and thanks for letting me know! The coming update should resolve those issues,
but I will verify that is fixed before it's released.

**Comment by Gmanicus** [comment]
This was resolved in version 2.0 :)

**Comment by Gmanicus** [comment]
Hi again Broccoli. I just staged 2.0.5 on the Chrome Webstore, which adds an alternative export/import file backup feature. It's not the most elegant solution, but it should work for now. You can access the export/import features via the help menu. I would expect this update to be published by Monday.

Have a great weekend!
