### ISSUE TITLE
There appears to be no syncing and exporting feature to save my created tabs.

### ISSUE THREAD

**Issue by kanannuruyevs** [Gmanicus/Youtube-Tabs#2]
If that's the case, I guess I should create tabs separately by using different versions of the browsers, which is highly inconvenient and a waste of my time. When I looked at the previous closed issue here, something about syncing to the cloud was mentioned, and you responded by making it a paid feature (correct me if I'm wrong). To be honest, I don't think that's a good idea, since many people are unlikely to pay to use proprietary software (especially if it's about to use a simple extension). In my opinion, it doesn't seem eloquent to tell people to pay you, thus I'd create a donation page and also make people not obligated to donate. I believe that choosing a good business model is always a good option, no matter how difficult it is to get it right. But other than that, I can understand your concern, as programming is so hard as it is and converting the work into some money here can make any sense with this circumstance. 

So, do you intend to take care of future development? Thanks.

**Comment by Gmanicus** [comment]
Hi Kanan,

I understand your opinion regarding this and appreciate you reaching out. Regarding the payments, my judgement was that I have put a considerable amount of work into this and will continue to provide the primary features of the extension for free while also trying to maintain it indefinitely, all in my own time.

In fact, I used to have a donation button within the extension that was in the help menu and would appear after each update, but only received one or two donations over 16mo (Which is not to say I don't appreciate those. I do appreciate those very much).

The cloud save feature was originally planned to make it possible to carry the tabs over to multiple computers. It was more of a nice-to-have than something that was absolutely necessary for most users, so I figured this would be a good candidate to charge a fee for under, for lack of a better term, a 'premium' tier, because that also incurs an additional charge for me in order to host the database & server to save that data, not to mention the extra work required to add an accounts system and keeping account data safe and secure all for that one feature (and other potential features down the line).

However, I will be adding an alternative save & import feature in the short-term future in order to prevent data loss. This alternative could be used to carry the data over to other computers, just not as conveniently. Hopefully that will be sufficient until can provide a cloud save feature in addition to that.

P.S: You brought to my attention that the License file was missing. This extension is under the MPL license. This extension is not proprietary and is open-source.

I will update this when that alternative is added to the extension. Thanks for using my extension!

**Comment by Gmanicus** [comment]
Hi again Kanan,

Update 2.0.5 has been staged on the Chrome Webstore and I would expect you should see it by Monday. This update includes the alternative export/import file backup feature, which should resolve this issue.

Have a great weekend!

**Comment by kanannuruyevs** [comment]
Hey Grant! Thanks for the update.

I primarily use this extension in Firefox as it is where I created my tabs. So, I'll check them out in Edge as soon as they appear in Firefox so that I might try the new feature you stated here.

**Comment by Gmanicus** [comment]
Sounds good, just pushed that to Firefox as well. They tend to approve within 1-2 days. 👍

**Comment by Gmanicus** [comment]
... Or under 5 minutes. WOW 😆

**Comment by kanannuruyevs** [comment]
I have already tested this feature, which works great. But I think I should prioritize my extension usage here, since I'm on dual boot and also using two browsers (the names I mentioned above) in there and that compels me to deal with the new feature multiple times at once, LOL. And I suppose having to be accountable for multitasking is a major annoyance to me.

Anyway, I believe that was a very good move because it prevents you from losing your data and keeps you on track when you want to transfer it to another browser or simply keep it because you don't want to lose your work unexpectedly. And now I might suggest that you make it cross-platform in the future, but I realize that's a lot of work, and not all suggestions will be possibly implemented in a practical sense.

**Comment by Gmanicus** [comment]
Hi Kanan! Glad to hear it's working great! Also sorry for the inconvenience with your setup 😅 

I do hope to enable this data to be saved to the cloud & automatically synced in the future, but I'm not sure when that will be at the moment. I'm working on a big project in my personal time, so I'll have to make time for it at some point.

**Comment by kanansnote** [comment]
Hi Grant! It's me again. The extension stopped working on Edge, and I'd like to know if you can investigate and fix this issue. Thanks.
