### ISSUE TITLE
Adding a button or having the enter key operate to properly close created tabs after giving them particular names.

### ISSUE THREAD

**Issue by kanannuruyevs** [Gmanicus/Youtube-Tabs#5]
Hi Grant. How's it going?

So I have a basic idea that is related to the previous closed issue #4. My suggestion is either adding a button or making the enter key work after naming tabs.

![Screenshot 2023-07-30  #175634(1)](https://github.com/Gmanicus/Youtube-Tabs/assets/99095303/b025267f-4a82-47f6-8db4-7c1e3853a37a)

When I try to create other tabs, either I should click somewhere to exit, which can work for Firefox, but not for Edge. In "Here", I think creating a button by calling it as "Done" or something like this would sound great to understand that it is supposed to be pressed to complete the naming process.

Hope you'll work on this issue.

**Comment by Gmanicus** [comment]
Hello Kanan! I'm doing well, thank you. I hope you have been as well.

>  ...I should click somewhere to exit, which can work for Firefox, but not for Edge.

That sounds like an issue. I can look into that.

> My suggestion is either adding a button or making the enter key work after naming tabs.

I like the enter key idea. That is a small enhancement that would make the UX a bit better. In the 2.0 UI overhaul, avoiding buttons was one of the design decisions that was made in favor of having edits save on change, so adding functionality for the enter key would be a better option.

Sorry for the delay. Would you like to revisit this?

**Comment by kanannuruyevs** [comment]
Yes, Grant. I can reopen the issue as I seeing your reply back made me rethink my decision which I appreciate you for that.

**Comment by kanannuruyevs** [comment]
Regarding the case that you mentioned about design decision, I can relate on that one. And with the enter key idea, I guess, thinking from an end-user perspective,  they should know if the operation is going to be done via enter key, so that the users wouldn't bother themselves to figure out this stuff by their own, which consumes a time and patience that I think it isn't intuitively applicable into human mind to do that easily. Thus, the basic idea here would be displaying a text like "Press Enter" in "Here" section.

 So yeah, that's my thoughts on it.

**Comment by Gmanicus** [comment]
I added the ability to additionally use the enter key to complete editing and close the tab menu when either creating or editing a tab. While I understand communicating features that may not be known by the user (And typically would lean that direction since that is definitely a good idea), using the enter key to complete forms is well-known on the web, so explaining that in the UI is more likely to be unnecessary and just add clutter. For those that are used to that behavior, that will now work. For others, they can still close the form by the usual option or by the enter key--whichever comes naturally.

Resolved in 2.0.9. Thanks.
